services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sw
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - docker-network
    volumes:
      - ./backend/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sw"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - docker-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
