export {
  proficiencyBonusForLevel,
  HIT_DIE_BY_CLASS,
  SPELLCASTING_ABILITY_BY_CLASS,
  resolveSpellcastingAbility,
  slotMaximaFromProgression,
  SAVE_PROFICIENCIES_BY_CLASS,
  SPEED_BY_RACE,
  DEFAULT_PROGRESSION_BY_CLASS,
  FULL_CASTER_SLOTS,
  HALF_CASTER_SLOTS,
  THIRD_CASTER_SLOTS,
  PACT_MAGIC_SLOTS,
  type PactMagicSlots,
} from './class-tables';
