export {
  SPELL_NAME_MAX_LENGTH,
  SPELL_DESCRIPTION_MAX_LENGTH,
  MAX_SLOT_COUNT,
  MAX_PIP_COUNT,
  MAX_SLOT_LEVEL,
  PROGRESSION_LABELS,
  PROGRESSION_OPTIONS,
  SPELL_LEVEL_OPTIONS,
} from './constants';

export { AddSpellMode, type SpellBody } from './types';
